@startuml
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName Arial
skinparam defaultFontSize 12
skinparam rectangle {
  BackgroundColor white
  BorderColor black
}
left to right direction

rectangle "Landing Page" as LandingPage
rectangle "Login Page" as LoginPage
rectangle "Register Page" as RegisterPage
rectangle "Forgot Password Page" as ForgotPasswordPage
rectangle "Reset Password Page" as ResetPasswordPage
rectangle "Verify Email Page" as VerifyEmailPage
rectangle "Terms Page" as TermsPage
rectangle "Privacy Page" as PrivacyPage
rectangle "Workspace Invitation Page" as WorkspaceInvitationPage
rectangle "Workspace Selection Page" as WorkspaceSelectionPage

LandingPage --> LoginPage
LandingPage --> RegisterPage

LoginPage --> ForgotPasswordPage
LoginPage --> RegisterPage
LoginPage --> TermsPage
LoginPage --> PrivacyPage

ForgotPasswordPage --> ResetPasswordPage
ResetPasswordPage --> LoginPage

RegisterPage --> VerifyEmailPage
RegisterPage --> LoginPage
VerifyEmailPage --> LoginPage

LoginPage --> WorkspaceSelectionPage
WorkspaceInvitationPage --> RegisterPage
WorkspaceInvitationPage --> WorkspaceSelectionPage

@enduml
