@startuml
skinparam monochrome true
skinparam shadowing false
skinparam linetype ortho
skinparam defaultFontName Arial
skinparam defaultFontSize 12
skinparam rectangle {
  BackgroundColor white
  BorderColor black
}
left to right direction

rectangle "Workspace Home Page" as WorkspaceHomePage
rectangle "Rooms Page" as RoomsPage
rectangle "Schedules Page" as SchedulesPage
rectangle "Join Translation Room Page" as JoinTranslationRoomPage
rectangle "Room Information Page" as RoomInformationPage
rectangle "Waiting Room Page" as WaitingRoomPage
rectangle "Live Meeting Page" as LiveMeetingPage
rectangle "Room Ended Summary Page" as RoomEndedSummaryPage
rectangle "Room Artifacts Page" as RoomArtifactsPage
rectangle "Feedback Page" as FeedbackPage
rectangle "History Page" as HistoryPage
rectangle "Documents Page" as DocumentsPage
rectangle "Document Details Page" as DocumentDetailsPage
rectangle "Members Page" as MembersPage

WorkspaceHomePage --> RoomsPage
WorkspaceHomePage --> SchedulesPage
WorkspaceHomePage --> HistoryPage
WorkspaceHomePage --> DocumentsPage
WorkspaceHomePage --> MembersPage

RoomsPage --> JoinTranslationRoomPage
RoomsPage --> RoomInformationPage
SchedulesPage --> RoomInformationPage

RoomInformationPage --> WaitingRoomPage
RoomInformationPage --> LiveMeetingPage
WaitingRoomPage --> LiveMeetingPage

LiveMeetingPage --> RoomEndedSummaryPage
RoomEndedSummaryPage --> RoomArtifactsPage
RoomEndedSummaryPage --> FeedbackPage
RoomEndedSummaryPage --> HistoryPage

DocumentsPage --> DocumentDetailsPage

@enduml
