@startuml
skinparam monochrome true
skinparam shadowing false
skinparam linetype ortho
skinparam defaultFontName Arial
skinparam defaultFontSize 12
skinparam rectangle {
  BackgroundColor white
  BorderColor black
}
left to right direction

rectangle "Workspace Home Page" as WorkspaceHomePage
rectangle "Rooms Page" as RoomsPage
rectangle "Schedules Page" as SchedulesPage
rectangle "Room Information Page" as RoomInformationPage
rectangle "Documents Page" as DocumentsPage
rectangle "Document Details Page" as DocumentDetailsPage
rectangle "Members Page" as MembersPage
rectangle "Billing Page" as BillingPage
rectangle "Plans Page" as PaymentPlansPage
rectangle "Payment Success Page" as PaymentSuccessPage
rectangle "Payment Cancelled Page" as PaymentCancelledPage
rectangle "Workspace Settings Page" as SettingsPage
rectangle "Advanced Workspace Page" as AdvancedWorkspacePage
rectangle "Workspace Dashboard Page" as DashboardPage
rectangle "Account Preferences Page" as AccountPreferencesPage
rectangle "Account Profile Page" as AccountProfilePage
rectangle "Voice Profiles Page" as VoiceProfilesPage

WorkspaceHomePage --> RoomsPage
WorkspaceHomePage --> SchedulesPage
WorkspaceHomePage --> DocumentsPage
WorkspaceHomePage --> MembersPage
WorkspaceHomePage --> SettingsPage
WorkspaceHomePage --> DashboardPage
WorkspaceHomePage --> VoiceProfilesPage
WorkspaceHomePage --> AccountPreferencesPage
WorkspaceHomePage --> AccountProfilePage

RoomsPage --> RoomInformationPage
SchedulesPage --> RoomInformationPage
DocumentsPage --> DocumentDetailsPage

DashboardPage --> BillingPage
DashboardPage --> PaymentPlansPage

SettingsPage --> BillingPage
SettingsPage --> AdvancedWorkspacePage

BillingPage --> PaymentPlansPage
PaymentPlansPage --> PaymentSuccessPage
PaymentPlansPage --> PaymentCancelledPage
PaymentSuccessPage --> BillingPage
PaymentCancelledPage --> PaymentPlansPage

@enduml
