@startuml
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName Arial
skinparam defaultFontSize 12
skinparam rectangle {
  BackgroundColor white
  BorderColor black
}
left to right direction

rectangle "Login Page" as LoginPage
rectangle "Admin Overview Page" as AdminOverviewPage
rectangle "Admin Workspaces Page" as AdminWorkspacesPage
rectangle "Admin Workspace Detail Page" as AdminWorkspaceDetailPage
rectangle "Admin Billing Page" as AdminBillingPage
rectangle "Admin Global Glossary Page" as AdminGlobalGlossaryPage

LoginPage --> AdminOverviewPage
AdminOverviewPage --> AdminWorkspacesPage
AdminOverviewPage --> AdminBillingPage
AdminOverviewPage --> AdminGlobalGlossaryPage

AdminWorkspacesPage --> AdminWorkspaceDetailPage
AdminWorkspaceDetailPage --> AdminWorkspacesPage

@enduml
