@startuml
skinparam monochrome true
skinparam shadowing false
skinparam linetype ortho
skinparam defaultFontName Arial
skinparam defaultFontSize 12
skinparam dpi 136
skinparam rectangle {
  BackgroundColor white
  BorderColor black
}
left to right direction

package "Host Actor" {
  rectangle "Workspace Rooms Page" as HostWorkspaceRoomsPage
  rectangle "Schedules Page" as HostSchedulesPage
  rectangle "Create Room Dialog" as CreateRoomDialog
  rectangle "Daily Recurrence Schedule Dialog" as DailyRecurrenceScheduleDialog
  rectangle "Setup Room Dialog" as HostSetupRoomDialog
  rectangle "Room Information Page" as HostRoomInformationPage
  rectangle "Live Meeting Page" as HostLiveMeetingPage
}

package "Participant Actor" {
  rectangle "Workspace Rooms Page" as ParticipantWorkspaceRoomsPage
  rectangle "Schedules Page" as ParticipantSchedulesPage
  rectangle "Join Translation Room Dialog" as JoinTranslationRoomDialog
  rectangle "Join Translation Room Page" as JoinTranslationRoomPage
  rectangle "Room Information Page" as ParticipantRoomInformationPage
  rectangle "Waiting Room Page" as WaitingRoomPage
  rectangle "Setup Room Dialog" as ParticipantSetupRoomDialog
  rectangle "Live Meeting Page" as ParticipantLiveMeetingPage
}

HostWorkspaceRoomsPage --> CreateRoomDialog
CreateRoomDialog --> DailyRecurrenceScheduleDialog
DailyRecurrenceScheduleDialog --> CreateRoomDialog
CreateRoomDialog --> HostSetupRoomDialog
CreateRoomDialog --> HostRoomInformationPage
HostSchedulesPage --> HostRoomInformationPage
HostSetupRoomDialog --> HostLiveMeetingPage
HostRoomInformationPage --> HostLiveMeetingPage

ParticipantWorkspaceRoomsPage --> JoinTranslationRoomDialog
JoinTranslationRoomDialog --> JoinTranslationRoomPage
JoinTranslationRoomPage --> ParticipantLiveMeetingPage
ParticipantWorkspaceRoomsPage --> ParticipantRoomInformationPage
ParticipantSchedulesPage --> ParticipantRoomInformationPage
ParticipantRoomInformationPage --> WaitingRoomPage
ParticipantRoomInformationPage --> ParticipantSetupRoomDialog
ParticipantSetupRoomDialog --> ParticipantLiveMeetingPage
WaitingRoomPage --> ParticipantSetupRoomDialog
WaitingRoomPage --> ParticipantLiveMeetingPage

@enduml
