@startuml
skinparam monochrome true
skinparam shadowing false
skinparam linetype ortho
skinparam defaultFontName Arial
skinparam defaultFontSize 12
skinparam dpi 136
skinparam rectangle {
  BackgroundColor white
  BorderColor black
}
left to right direction

package "Create And Schedule Meeting" {
  rectangle "Workspace Rooms Page" as ScheduleWorkspaceRoomsPage
  rectangle "Create Room Dialog" as CreateRoomDialog
  rectangle "Daily Recurrence Schedule Dialog" as DailyRecurrenceScheduleDialog
}

package "Review And Start Room" {
  rectangle "Schedules Page" as SchedulesPage
  rectangle "Room Information Page" as RoomInformationPage
  rectangle "Setup Room Dialog" as SetupRoomDialog
}

package "Join By Meeting Code" {
  rectangle "Workspace Rooms Page" as JoinWorkspaceRoomsPage
  rectangle "Join Translation Room Dialog" as JoinTranslationRoomDialog
  rectangle "Join Translation Room Page" as JoinTranslationRoomPage
}

package "Waiting And Live Session" {
  rectangle "Waiting Room Page" as WaitingRoomPage
  rectangle "Live Meeting Page" as LiveMeetingPage
}

ScheduleWorkspaceRoomsPage --> CreateRoomDialog
CreateRoomDialog --> DailyRecurrenceScheduleDialog
DailyRecurrenceScheduleDialog --> CreateRoomDialog
CreateRoomDialog --> SetupRoomDialog
CreateRoomDialog --> RoomInformationPage
SchedulesPage --> RoomInformationPage

RoomInformationPage --> LiveMeetingPage
RoomInformationPage --> WaitingRoomPage
RoomInformationPage --> SetupRoomDialog
SetupRoomDialog --> LiveMeetingPage
WaitingRoomPage --> SetupRoomDialog
WaitingRoomPage --> LiveMeetingPage

JoinWorkspaceRoomsPage --> JoinTranslationRoomDialog
JoinTranslationRoomDialog --> JoinTranslationRoomPage
JoinTranslationRoomPage --> LiveMeetingPage

@enduml
