<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\WarpTalk.PaymentService.Application\WarpTalk.PaymentService.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Stripe.net" Version="51.1.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
