// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WarpTalk.BillingService.Infrastructure.Persistence;

#nullable disable

namespace WarpTalk.BillingService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    partial class BillingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("billing")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WarpTalk.BillingService.Domain.Entities.QuotaAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("QuotaAuditLogs", "billing");
                });

            modelBuilder.Entity("WarpTalk.BillingService.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BaseQuotaMinutes")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeaturesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PriceVnd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans", "billing");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            BaseQuotaMinutes = 30m,
                            CreatedAt = new DateTime(2026, 4, 29, 7, 41, 43, 388, DateTimeKind.Utc).AddTicks(6406),
                            FeaturesJson = "{}",
                            IsActive = true,
                            MaxParticipants = 5,
                            Name = "Free",
                            PriceVnd = 0m
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            BaseQuotaMinutes = 500m,
                            CreatedAt = new DateTime(2026, 4, 29, 7, 41, 43, 388, DateTimeKind.Utc).AddTicks(7238),
                            FeaturesJson = "{}",
                            IsActive = true,
                            MaxParticipants = 25,
                            Name = "Pro",
                            PriceVnd = 199000m
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            BaseQuotaMinutes = 1000m,
                            CreatedAt = new DateTime(2026, 4, 29, 7, 41, 43, 388, DateTimeKind.Utc).AddTicks(7244),
                            FeaturesJson = "{}",
                            IsActive = true,
                            MaxParticipants = 100,
                            Name = "Premium",
                            PriceVnd = 499000m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            BaseQuotaMinutes = 10000m,
                            CreatedAt = new DateTime(2026, 4, 29, 7, 41, 43, 388, DateTimeKind.Utc).AddTicks(7254),
                            FeaturesJson = "{}",
                            IsActive = true,
                            MaxParticipants = 1000,
                            Name = "Enterprise",
                            PriceVnd = 0m
                        });
                });

            modelBuilder.Entity("WarpTalk.BillingService.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountVnd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("OrderCode")
                        .HasColumnType("bigint");

                    b.Property<string>("PayOsTransactionId")
                        .HasColumnType("text");

                    b.Property<decimal>("PurchasedMinutes")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderCode")
                        .IsUnique();

                    b.ToTable("Transactions", "billing");
                });

            modelBuilder.Entity("WarpTalk.BillingService.Domain.Entities.UsageQuota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ConsumedMinutes")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CycleEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CycleStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalAllocatedMinutes")
                        .HasColumnType("decimal(18,4)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("WorkspaceId")
                        .IsUnique();

                    b.ToTable("UsageQuotas", "billing");
                });

            modelBuilder.Entity("WarpTalk.BillingService.Domain.Entities.UsageQuota", b =>
                {
                    b.HasOne("WarpTalk.BillingService.Domain.Entities.SubscriptionPlan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plan");
                });
#pragma warning restore 612, 618
        }
    }
}
