@startuml
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName Arial
skinparam defaultFontSize 12
skinparam rectangle {
  BackgroundColor white
  BorderColor black
}
left to right direction

rectangle "Workspace Home Page" as WorkspaceHome
rectangle "Notifications Center Modal" as NotificationsModal
rectangle "Notification Preferences Page" as NotificationPreferencesPage

WorkspaceHome --> NotificationsModal
NotificationsModal --> NotificationPreferencesPage
NotificationPreferencesPage --> WorkspaceHome

@enduml
