using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using WarpTalk.BillingService.Application.DTOs;
using WarpTalk.BillingService.Application.Interfaces;
using WarpTalk.BillingService.Application.Mappers;
using WarpTalk.BillingService.Application.Helpers;
using WarpTalk.BillingService.Domain.Interfaces;

using WarpTalk.BillingService.Domain.Constants;
using WarpTalk.Shared;

namespace WarpTalk.BillingService.Application.Services;

public class CreditService : ICreditService
{
    private readonly IUnitOfWork _unitOfWork;
    private readonly ILogger<CreditService> _logger;
    private readonly IBillingMessagePublisher _messagePublisher;
    private readonly IConfiguration _configuration;
    private readonly IWorkspaceClient _workspaceClient;
    private readonly INotificationClient? _notificationClient;

    public CreditService(
        IUnitOfWork unitOfWork,
        ILogger<CreditService> logger,
        IBillingMessagePublisher messagePublisher,
        IConfiguration configuration,
        IWorkspaceClient workspaceClient,
        INotificationClient? notificationClient = null)
    {
        _unitOfWork = unitOfWork;
        _logger = logger;
        _messagePublisher = messagePublisher;
        _configuration = configuration;
        _workspaceClient = workspaceClient;
        _notificationClient = notificationClient;
    }



    public async Task<Result<CreditBalanceDto>> GetWorkspaceCreditsAsync(
        Guid workspaceId, CancellationToken cancellationToken = default)
    {
        try
        {
            var subResult = await SubscriptionHelper.GetActiveSubscriptionAsync(_unitOfWork, workspaceId, cancellationToken);
            if (!subResult.IsSuccess)
                return Result.Failure<CreditBalanceDto>(subResult.Error, subResult.ErrorCode);
            var sub = subResult.Value;

            return Result.Success(sub.ToCreditBalanceDto(workspaceId));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, BillingMessageConstants.LogMessages.ErrorGettingWorkspaceCredits, workspaceId);
            return Result.Failure<CreditBalanceDto>(ApiMessageConstants.ErrorMessages.BillingInternalError, ErrorCodes.InternalServerError);
        }
    }

    public Task<Result<CreditTransactionDto>> ConsumeCreditsDirectlyAsync(
        Guid workspaceId, ConsumeCreditsRequest request, CancellationToken cancellationToken = default)
    {
        return ConcurrencyRetryHelper.ExecuteWithConcurrencyRetryAsync(_unitOfWork, _logger, workspaceId, async () =>
        {
            if (request.Amount <= 0)
                return Result.Failure<CreditTransactionDto>(ApiMessageConstants.ErrorMessages.BillingInvalidAmount, ErrorCodes.BillingInvalidAmount);

            var subResult = await SubscriptionHelper.GetActiveSubscriptionAsync(_unitOfWork, workspaceId, cancellationToken);
            if (!subResult.IsSuccess)
                return Result.Failure<CreditTransactionDto>(subResult.Error, subResult.ErrorCode);
            var sub = subResult.Value;

            if (sub.CreditsRemaining < request.Amount)
                return Result.Failure<CreditTransactionDto>(ApiMessageConstants.ErrorMessages.BillingInsufficientCredits, ErrorCodes.BillingInsufficientCredits);

            sub.CreditsRemaining -= request.Amount;
            sub.CreditsUsedThisCycle += request.Amount;
            sub.UpdatedAt = DateTime.UtcNow;
            _unitOfWork.SubscriptionRepository.Update(sub);

            var transaction = request.ToEntity(sub);
            await _unitOfWork.CreditTransactionRepository.AddAsync(transaction, cancellationToken);

            var usage = request.ToUsageRecord(sub);
            await _unitOfWork.UsageRecordRepository.AddAsync(usage, cancellationToken);
            await _unitOfWork.SaveChangesAsync(cancellationToken);

            await BillingNotificationHelper.PublishCreditUpdateAsync(
                _messagePublisher,
                _logger,
                NotificationMapper.ToCreditsUpdatedMessage(sub.UserId, sub.CreditsRemaining, string.Empty, string.Empty),
                cancellationToken);

            return Result.Success(transaction.ToDto());
        }, cancellationToken);
    }

    public Task<Result<CreditBalanceDto>> TopUpCreditsAsync(
        Guid workspaceId, TopUpRequest request, CancellationToken cancellationToken = default)
    {
        return Task.FromResult(Result.Failure<CreditBalanceDto>(
            ApiMessageConstants.ErrorMessages.BillingDirectTopUpDisabled,
            ErrorCodes.Forbidden));
    }

    // TODO: This method is for internal testing/simulation only and does NOT integrate with real Stripe.
    // - stripeInvoiceId is a randomly generated mock ID, not a real Stripe invoice ID.
    // - The invoice PdfUrl generated by ToSimulatedEntity() is a non-functional placeholder.
    // When real Stripe integration is ready, this method should be replaced by the actual
    // Stripe Checkout or Payment Intent flow, and PdfUrl should be populated from the
    // Stripe Webhook event payload (invoice.payment_succeeded → invoice_pdf field).
    public async Task<Result<object>> SimulatePaymentAsync(Guid workspaceId, decimal amount, string currency, CancellationToken cancellationToken = default)
    {
        if (amount <= 0)
            return Result.Failure<object>(ApiMessageConstants.ErrorMessages.BillingInvalidAmount, ErrorCodes.BillingInvalidAmount);

        var subResult = await SubscriptionHelper.GetActiveSubscriptionAsync(_unitOfWork, workspaceId, cancellationToken);
        if (!subResult.IsSuccess)
            return Result.Failure<object>(subResult.Error, subResult.ErrorCode);
        var sub = subResult.Value;

        var paymentId = Guid.NewGuid();
        // TODO: Mock ID only — not a real Stripe invoice ID. Replace with actual Stripe invoice ID from webhook.
        var stripeInvoiceId = PaymentConstants.StripePrefixes.Invoice + Guid.NewGuid().ToString("N")[..14];

        var paymentTx = new SimulatedPaymentCreationRequest(
            sub,
            paymentId,
            stripeInvoiceId,
            amount,
            currency).ToSimulatedEntity();
        await _unitOfWork.PaymentRepository.AddAsync(paymentTx, cancellationToken);

        var invoice = paymentTx.ToSimulatedEntity();
        await _unitOfWork.InvoiceRepository.AddAsync(invoice, cancellationToken);

        await _unitOfWork.SaveChangesAsync(cancellationToken);

        return Result.Success<object>(new { message = BillingMessageConstants.SuccessMessages.SimulatePaymentMessage, invoiceId = invoice.Id, stripeInvoiceId });
    }

    public async Task<Result<PaginatedResponse<CreditTransactionDto>>> GetCreditHistoryAsync(
        Guid workspaceId,
        CreditHistoryQuery query,
        CancellationToken cancellationToken = default)
    {
        var subs = await _unitOfWork.SubscriptionRepository.FindAsync(
            s => s.WorkspaceId == workspaceId && s.DeletedAt == null,
            cancellationToken);

        var subIds = subs.Select(s => s.Id).ToList();
        if (subIds.Count == 0)
            return Result.Failure<PaginatedResponse<CreditTransactionDto>>(
                ApiMessageConstants.ErrorMessages.BillingSubscriptionNotFound,
                ErrorCodes.BillingSubscriptionNotFound);

        var page = await _unitOfWork.CreditTransactionRepository.GetHistoryPageAsync(
            BillingQueryHelper.ToCreditTransactionHistoryFilter(query, subIds),
            cancellationToken);

        return Result.Success(PaginatedResponse<CreditTransactionDto>.Create(
            page.Items.ToDtoList(workspaceId), page.TotalCount, page.PageNumber, page.PageSize));
    }

    public async Task<Result<PaginatedResponse<CreditTransactionDto>>> GetGlobalCreditHistoryAsync(
        CreditHistoryQuery query,
        CancellationToken cancellationToken = default)
    {
        var page = await _unitOfWork.CreditTransactionRepository.GetHistoryPageAsync(
            BillingQueryHelper.ToCreditTransactionHistoryFilter(query, null),
            cancellationToken);

        var dtos = page.Items.ToDtoList();

        try
        {
            var workspaceIds = BillingQueryHelper.GetWorkspaceIds(dtos);

            if (workspaceIds.Length > 0)
            {
                var workspaceNames = await _unitOfWork.CreditTransactionRepository.GetWorkspaceNamesAsync(workspaceIds, cancellationToken);
                dtos = BillingQueryHelper.ApplyWorkspaceNames(dtos, workspaceNames);
            }
        }
        catch (Exception wsEx)
        {
            _logger.LogWarning(wsEx, BillingMessageConstants.LogMessages.FailedToResolveWorkspaceNames);
        }

        return Result.Success(PaginatedResponse<CreditTransactionDto>.Create(dtos, page.TotalCount, page.PageNumber, page.PageSize));
    }

    public Task<Result<CreditTransactionDto>> ManualAdjustCreditsAsync(
        Guid workspaceId,
        ManualAdjustCreditsRequest request,
        CancellationToken cancellationToken = default)
    {
        if (request.Amount == 0)
            return Task.FromResult(Result.Failure<CreditTransactionDto>(ApiMessageConstants.ErrorMessages.BillingInvalidAmount, ErrorCodes.BillingInvalidAmount));
        if (string.IsNullOrWhiteSpace(request.AdminUserId))
            return Task.FromResult(Result.Failure<CreditTransactionDto>(ApiMessageConstants.ErrorMessages.BillingAccessDenied, ErrorCodes.Forbidden));

        return ConcurrencyRetryHelper.ExecuteWithConcurrencyRetryAsync(_unitOfWork, _logger, workspaceId, async () =>
        {
            var subResult = await SubscriptionHelper.GetActiveSubscriptionAsync(_unitOfWork, workspaceId, cancellationToken);
            if (!subResult.IsSuccess)
                return Result.Failure<CreditTransactionDto>(subResult.Error, subResult.ErrorCode);
            var sub = subResult.Value;

            sub.ApplyAdjustment(request.Amount);
            _unitOfWork.SubscriptionRepository.Update(sub);

            var adjustmentTransaction = request.ToEntity(sub);

            await _unitOfWork.CreditTransactionRepository.AddAsync(adjustmentTransaction, cancellationToken);
            await _unitOfWork.SaveChangesAsync(cancellationToken);

            var notificationTitle = request.Amount > 0
                ? BillingMessageConstants.AdjustmentMessages.AddedTitle
                : BillingMessageConstants.AdjustmentMessages.DeductedTitle;

            var notificationContent = string.Format(
                BillingMessageConstants.AdjustmentMessages.ContentTemplate,
                request.Amount > 0 ? "+" : "",
                request.Amount,
                adjustmentTransaction.Description);

            await BillingNotificationHelper.PublishCreditUpdateAsync(
                _messagePublisher,
                _logger,
                NotificationMapper.ToCreditsUpdatedMessage(sub.UserId, sub.CreditsRemaining, notificationTitle, notificationContent),
                cancellationToken);

            return Result.Success(adjustmentTransaction.ToDto());
        }, cancellationToken);
    }




}
