// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WarpTalk.WorkspaceService.Infrastructure.Persistence;

#nullable disable

namespace WarpTalk.WorkspaceService.Infrastructure.Migrations
{
    [DbContext(typeof(WorkspaceDbContext))]
    partial class WorkspaceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "artifact_type", new[] { "TRANSCRIPT_EXPORT", "SUMMARY_EXPORT", "DEBUG_LOG", "OPTIONAL_RECORDING", "AUDIO_SAMPLE" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "consent_status", new[] { "GRANTED", "REVOKED", "EXPIRED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "job_status", new[] { "QUEUED", "PROCESSING", "COMPLETED", "FAILED", "CANCELLED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "notification_status", new[] { "PENDING", "SENT", "DELIVERED", "FAILED", "READ" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "participant_status", new[] { "INVITED", "WAITING", "CONNECTED", "DISCONNECTED", "LEFT", "KICKED", "REJECTED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "room_status", new[] { "SCHEDULED", "WAITING", "IN_PROGRESS", "PAUSED", "ENDED", "CANCELLED", "EXPIRED", "FAILED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ticket_status", new[] { "OPEN", "IN_PROGRESS", "RESOLVED", "CLOSED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "transcript", "correction_status", new[] { "PENDING", "ACCEPTED", "REJECTED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "transcript", "correction_type", new[] { "STT", "TRANSLATION" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "transcript", "transcript_status", new[] { "RECORDING", "FINALIZING", "FINALIZED", "ARCHIVED" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WarpTalk.WorkspaceService.Domain.Entities.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<bool>("AllowExternalCollaboration")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_external_collaboration");

                    b.Property<bool>("AllowSubdomains")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_subdomains");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<bool>("RequireVerifiedDomainForInternal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("require_verified_domain_for_internal");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("settings")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("workspaces_pkey");

                    b.HasIndex(new[] { "Slug" }, "workspaces_slug_key")
                        .IsUnique();

                    b.ToTable("workspaces", "workspace");
                });

            modelBuilder.Entity("WarpTalk.WorkspaceService.Domain.Entities.WorkspaceDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<bool>("AiEligible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ai_eligible");

                    b.Property<string>("AiUsagePolicy")
                        .HasColumnType("jsonb")
                        .HasColumnName("ai_usage_policy");

                    b.Property<string>("BusinessDomain")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("business_domain");

                    b.Property<string>("ConfidentialityLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("confidentiality_level")
                        .HasDefaultValueSql("'public_internal'::character varying");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("DetectedLanguage")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("detected_language");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_type");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("file_extension");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("IndexVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("index_version");

                    b.Property<string>("IngestionStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("ingestion_status")
                        .HasDefaultValueSql("'pending'::character varying");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sensitive");

                    b.Property<string>("Keywords")
                        .HasColumnType("jsonb")
                        .HasColumnName("keywords");

                    b.Property<DateTime?>("LastIndexedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_indexed_at");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mime_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("RetentionState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("retention_state")
                        .HasDefaultValueSql("'active'::character varying");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceLanguage")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source_language");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'active'::character varying");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("storage_provider");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UploadedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("workspace_documents_pkey");

                    b.HasIndex(new[] { "WorkspaceId", "AiEligible" }, "idx_workspace_documents_workspace_ai");

                    b.HasIndex(new[] { "WorkspaceId", "ConfidentialityLevel" }, "idx_workspace_documents_workspace_confidentiality");

                    b.HasIndex(new[] { "WorkspaceId" }, "idx_workspace_documents_workspace_id");

                    b.HasIndex(new[] { "WorkspaceId", "SourceLanguage" }, "idx_workspace_documents_workspace_lang");

                    b.HasIndex(new[] { "WorkspaceId", "RetentionState" }, "idx_workspace_documents_workspace_retention");

                    b.HasIndex(new[] { "WorkspaceId", "Status" }, "idx_workspace_documents_workspace_status");

                    b.ToTable("workspace_documents", "workspace");
                });

            modelBuilder.Entity("WarpTalk.WorkspaceService.Domain.Entities.WorkspaceDocumentAccessPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("effect");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("permission");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectKey")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("subject_key");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("subject_type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("workspace_document_access_policies_pkey");

                    b.HasIndex("WorkspaceId");

                    b.HasIndex(new[] { "DocumentId" }, "idx_doc_access_policies_doc_id");

                    b.HasIndex(new[] { "DocumentId", "SubjectType", "SubjectId" }, "idx_doc_access_policies_lookup");

                    b.ToTable("workspace_document_access_policies", "workspace");
                });

            modelBuilder.Entity("WarpTalk.WorkspaceService.Domain.Entities.WorkspaceDocumentAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<DateTime>("ActionAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("action_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("workspace_document_audits_pkey");

                    b.HasIndex(new[] { "ActorId", "ActionAt" }, "idx_workspace_doc_audits_actor_action");

                    b.HasIndex(new[] { "DocumentId" }, "idx_workspace_doc_audits_doc_id");

                    b.HasIndex(new[] { "WorkspaceId", "ActionAt" }, "idx_workspace_doc_audits_workspace_action");

                    b.ToTable("workspace_document_audits", "workspace");
                });

            modelBuilder.Entity("WarpTalk.WorkspaceService.Domain.Entities.WorkspaceInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InvitedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by");

                    b.Property<Guid?>("MatchedDomainId")
                        .HasColumnType("uuid")
                        .HasColumnName("matched_domain_id");

                    b.Property<string>("MembershipType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("membership_type")
                        .HasDefaultValueSql("'internal'::character varying");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'pending'::character varying");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("workspace_invitations_pkey");

                    b.HasIndex("WorkspaceId");

                    b.HasIndex(new[] { "TokenHash" }, "workspace_invitations_token_hash_key")
                        .IsUnique();

                    b.ToTable("workspace_invitations", "workspace");
                });

            modelBuilder.Entity("WarpTalk.WorkspaceService.Domain.Entities.WorkspaceKnowledgeGlossary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("BusinessDomain")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("business_domain");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Definition")
                        .HasColumnType("text")
                        .HasColumnName("definition");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("PartOfSpeech")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("part_of_speech");

                    b.Property<string>("PreferredTranslation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("preferred_translation");

                    b.Property<string>("SourceLanguage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source_language");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'active'::character varying");

                    b.Property<string>("TargetLanguage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("target_language");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("term");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("UsageNote")
                        .HasColumnType("text")
                        .HasColumnName("usage_note");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("workspace_knowledge_glossaries_pkey");

                    b.HasIndex(new[] { "WorkspaceId", "BusinessDomain", "SourceLanguage" }, "idx_workspace_glossaries_lookup");

                    b.HasIndex(new[] { "WorkspaceId", "BusinessDomain", "SourceLanguage", "TargetLanguage", "Term" }, "workspace_knowledge_glossarie_workspace_id_business_domain__key")
                        .IsUnique();

                    b.ToTable("workspace_knowledge_glossaries", "workspace");
                });

            modelBuilder.Entity("WarpTalk.WorkspaceService.Domain.Entities.WorkspaceMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("MembershipType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("membership_type")
                        .HasDefaultValueSql("'internal'::character varying");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<Guid?>("RemovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("removed_by");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'active'::character varying");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("workspace_members_pkey");

                    b.HasIndex(new[] { "WorkspaceId", "UserId" }, "workspace_members_workspace_id_user_id_key")
                        .IsUnique();

                    b.ToTable("workspace_members", "workspace");
                });

            modelBuilder.Entity("WarpTalk.WorkspaceService.Domain.Entities.WorkspaceVerifiedDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("domain");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'pending'::character varying");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("VerificationMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("verification_method");

                    b.Property<string>("VerificationToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("verification_token");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.Property<Guid?>("VerifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("verified_by");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("workspace_verified_domains_pkey");

                    b.HasIndex("WorkspaceId");

                    b.HasIndex(new[] { "Domain" }, "idx_workspace_verified_domains_unique_verified")
                        .IsUnique()
                        .HasFilter("((status)::text = 'verified'::text)");

                    b.ToTable("workspace_verified_domains", "workspace");
                });

            modelBuilder.Entity("WarpTalk.WorkspaceService.Domain.Entities.WorkspaceDocument", b =>
                {
                    b.HasOne("WarpTalk.WorkspaceService.Domain.Entities.Workspace", "Workspace")
                        .WithMany("WorkspaceDocuments")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("workspace_documents_workspace_id_fkey");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("WarpTalk.WorkspaceService.Domain.Entities.WorkspaceDocumentAccessPolicy", b =>
                {
                    b.HasOne("WarpTalk.WorkspaceService.Domain.Entities.WorkspaceDocument", "Document")
                        .WithMany("WorkspaceDocumentAccessPolicies")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("workspace_document_access_policies_document_id_fkey");

                    b.HasOne("WarpTalk.WorkspaceService.Domain.Entities.Workspace", "Workspace")
                        .WithMany("WorkspaceDocumentAccessPolicies")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("workspace_document_access_policies_workspace_id_fkey");

                    b.Navigation("Document");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("WarpTalk.WorkspaceService.Domain.Entities.WorkspaceDocumentAudit", b =>
                {
                    b.HasOne("WarpTalk.WorkspaceService.Domain.Entities.WorkspaceDocument", "Document")
                        .WithMany("WorkspaceDocumentAudits")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("workspace_document_audits_document_id_fkey");

                    b.HasOne("WarpTalk.WorkspaceService.Domain.Entities.Workspace", "Workspace")
                        .WithMany("WorkspaceDocumentAudits")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("workspace_document_audits_workspace_id_fkey");

                    b.Navigation("Document");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("WarpTalk.WorkspaceService.Domain.Entities.WorkspaceInvitation", b =>
                {
                    b.HasOne("WarpTalk.WorkspaceService.Domain.Entities.Workspace", "Workspace")
                        .WithMany("WorkspaceInvitations")
                        .HasForeignKey("WorkspaceId")
                        .IsRequired()
                        .HasConstraintName("workspace_invitations_workspace_id_fkey");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("WarpTalk.WorkspaceService.Domain.Entities.WorkspaceKnowledgeGlossary", b =>
                {
                    b.HasOne("WarpTalk.WorkspaceService.Domain.Entities.Workspace", "Workspace")
                        .WithMany("WorkspaceKnowledgeGlossaries")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("workspace_knowledge_glossaries_workspace_id_fkey");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("WarpTalk.WorkspaceService.Domain.Entities.WorkspaceMember", b =>
                {
                    b.HasOne("WarpTalk.WorkspaceService.Domain.Entities.Workspace", "Workspace")
                        .WithMany("WorkspaceMembers")
                        .HasForeignKey("WorkspaceId")
                        .IsRequired()
                        .HasConstraintName("workspace_members_workspace_id_fkey");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("WarpTalk.WorkspaceService.Domain.Entities.WorkspaceVerifiedDomain", b =>
                {
                    b.HasOne("WarpTalk.WorkspaceService.Domain.Entities.Workspace", "Workspace")
                        .WithMany("WorkspaceVerifiedDomains")
                        .HasForeignKey("WorkspaceId")
                        .IsRequired()
                        .HasConstraintName("workspace_verified_domains_workspace_id_fkey");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("WarpTalk.WorkspaceService.Domain.Entities.Workspace", b =>
                {
                    b.Navigation("WorkspaceDocumentAccessPolicies");

                    b.Navigation("WorkspaceDocumentAudits");

                    b.Navigation("WorkspaceDocuments");

                    b.Navigation("WorkspaceInvitations");

                    b.Navigation("WorkspaceKnowledgeGlossaries");

                    b.Navigation("WorkspaceMembers");

                    b.Navigation("WorkspaceVerifiedDomains");
                });

            modelBuilder.Entity("WarpTalk.WorkspaceService.Domain.Entities.WorkspaceDocument", b =>
                {
                    b.Navigation("WorkspaceDocumentAccessPolicies");

                    b.Navigation("WorkspaceDocumentAudits");
                });
#pragma warning restore 612, 618
        }
    }
}
